# Generated by Django 2.1.7 on 2019-09-27 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Assigner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='time',
        ),
        migrations.AddField(
            model_name='interview',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
