# Generated by Django 2.1.7 on 2019-09-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assigner', '0003_auto_20190927_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
